clients:
  - name: "Altum"
    aliases: ["Altum", "Altum.ai", "ALTUM", "Altum AI", "altum"]
  - name: "Forward Financing"
    aliases: ["Forward Financing", "ForwardFinancing", "Forward Financing"]
  - name: "Ideal Prediction"
    aliases: ["Ideal Prediction", "Ideal", "IdealPrediction"]
- name: "Chromatics"
    aliases: ["Chromatics", "chromatics", "Chromatics.ai", "chromatics.ai", "chromatics ai", "Chromatics AI"]
- name: "AFAB"
    aliases: ["AFAB", "afab"]
- name: "CARPEDM"
    aliases: ["CARPEDM", "carpedm", "CarpeDiem"]
- name: "Portillos"
    aliases: ["Portillos", "Portillo's", "portillos"]
- name: "Newton"
    aliases: ["Newton Labs", "newton", "newtons"]
- name: "QU"
    aliases: ["qu", "Qu", "QU Beyond", "qu beyond", "QU beyond"]
- name: "CFI"
    aliases: ["CFI", "cfi"]
- name: "GFW"
    aliases: ["GFW", "gfw"]
- name: "La Pampa"
    aliases: ["La Pampa", "APE", "ape", "la pampa"]
- name: "Kerry"
    aliases: ["Kerry", "kerry"]
- name: "Podifi"
    aliases: ["Podifi", "podifi"]
- name: "Celara Labs"
    aliases: ["Celara Labs", "celara labs", "celara", "Celara", "CELARA", "Tryni", "Tryni 2.0"]
- name: "Public Relay"
  aliases: ["Public Relay", "PublicRelay", "public relay"]